
services:
- type: web
  name: flask-postgres-api
  env: python
  repo: https://github.com/500BrainNotWorking/Student-Conduct-Tracker-1.git    
  plan: free
  branch: main
  healthCheckPath: /healthcheck
  buildCommand: "pip install -r requirements.txt"
  startCommand: "gunicorn wsgi:app"
  envVars:
  - fromGroup: flask-postgres-api-settings
  - key: POSTGRES_URL
    fromDatabase:
      name: flask-postgres-api-db
      property: host
  - key: POSTGRES_USER
    fromDatabase:
      name: flask-postgres-api-db
      property: user
  - key: POSTGRES_PASSWORD
    fromDatabase:
      name: flask-postgres-api-db
      property: password
  - key: POSTGRES_DB
    fromDatabase:
      name: flask-postgres-api-db
      property: database 
  - key: SQLALCHEMY_DATABASE_URI
    value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_URL)/$(POSTGRES_DB)

envVarGroups:
- name: flask-postgres-api-settings
  envVars:
  - key: ENV
    value: production
  - key: FLASK_APP
    value: wsgi.py


  # - key: SECRET_KEY
  #   value: secret-key #Add rthe secret key here
    

databases:
- name: flask-postgres-api-db
  plan: free
  databaseName: mydb